version: "3"
services:
  api:
    # replace username/repo:tag with your name and image details
    image: green_finance/gfp-api
    build: ./apis/main
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "3030:3030"
    networks:
      - gfp
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postchain"
      POSTGRES_PASSWORD: ""
  db_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


networks:
  ? gfp
